### ISSUE TITLE
unable to fetch imdb.csv ?

### ISSUE THREAD

**Issue by projectje** [aaachen/IMDb-Obsidian#1]
Unable to fetch imdb csv. Error: Error: Request failed, status 404
    at new t (app.js:1:1977769)
    at qG (app.js:1:1977961)
    at app.js:1:1978638
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)

**Comment by aaachen** [comment]
Is the list url correct? Something in the format of https://www.imdb.com/list/ls523701947

**Comment by projectje** [comment]
it's like https://www.imdb.com/user/ur7456123/ratings/export (though changed the exact id)

**Comment by DarkWolf7** [comment]
I don't think the instructions as noted in the readme.md are accurate anymore. I don't have an export link on the bottom (not one that I can do a "copy link" from anyway), and the export link creates a one time export csv that gets dumped in an s3 bucket which isn't parseable by the plugin

**Comment by corani** [comment]
The `/lists/ls..../export` URL no longer works. Apparently this was removed a few months ago: https://www.reddit.com/r/imdb/comments/1dqi940/bulk_downloading_lists_via_the_export_endpoint_no/

**Comment by intothegarden** [comment]
Anyone found a workaround for this? 

So after IMDB have done their changes, it looks like it gets the CSV from a different location.

# Instructions
1. Go to your [exports page in IMDB](https://www.imdb.com/exports/) 
2. Hit f12 to bring open the dev tools. 
3. Click the 'export' button on the list that you want on the exports page
4. It will try to save the CSV file for the list you selected (save it anywhere)
5. In dev tools, go to the Network tab and it will show you where it's actually getting the CSV file from (this example is from '100 Top Disney Films'): 

<img width="1862" height="257" alt="Image" src="https://github.com/user-attachments/assets/7cdc641d-1145-41cb-a59e-1c27dc41dbae" />

Unfortunately, plugging this URL into the Obsidian plugin doesn't work still.

**Comment by ricardojcr** [comment]
Any workarounds? I can't make it work either.
