### ISSUE TITLE
can't get note

### ISSUE THREAD

**Issue by louwelyn-jeremy** [aaachen/IMDb-Obsidian#3]
Hi!
i think my plugin's parameters  are correct , but i don't have file creation.
il console, i can find this message:
plugin:imdb-sync:729 omdb returned invalid response for id=[].
it  talks about 1529 items, but my list inly have 1 item!

**Comment by OPEN1004MIND** [comment]
plugin:imdb-sync:729 omdb returned invalid response for id=[]. Response: 
Object

or 

plugin:imdb-sync:689 Unable to fetch imdb csv. Error: Error: Request failed, status 404
    at new t (app.js:1:1231041)
    at zA (app.js:1:1231233)
    at app.js:1:1231912
    at app.js:1:239667
    at Object.next (app.js:1:239772)
    at a (app.js:1:238490)

**I am having the same problem and getting an error**

It seems that the plugin no longer works with that URL, according to someone else's information. See the link below.
https://www.reddit.com/r/imdb/comments/1dqi940/bulk_downloading_lists_via_the_export_endpoint_no/
